version: "2"

services:
  
  cuckoodaemon:
    image: blacktop/cuckoo:2.0
    command: daemon
    container_name: cuckoodaemon
    expose:
      - "2042"
    volumes:
      - /docker/cuckoo/data/cuckoo-tmp:/tmp/cuckoo-tmp/
      - /docker/cuckoo/data/cuckoo-storage:/cuckoo/storage/
    networks:
      - cuckoo
    env_file:
      - ./cuckoo/2.0/config-file.env
    depends_on:
      - cuckooelasticsearch
      - cuckoomongo
      - cuckoopostgres
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  cuckooweb:
    image: blacktop/cuckoo:2.0
    container_name: cuckooweb
    depends_on:
      - cuckoomongo
      - cuckooelasticsearch
      - cuckoopostgres
    ports:
      - "8080:31337"
    command: web
    volumes:
      - /docker/cuckoo/data/cuckoo-tmp:/tmp/cuckoo-tmp/
      - /docker/cuckoo/data/cuckoo-storage:/cuckoo/storage/
    networks:
      - cuckoo
    env_file:
      - ./cuckoo/2.0/config-file.env
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  cuckooapi:
    depends_on:
      - cuckoopostgres
      - cuckoomongo
      - cuckooelasticsearch
    image: blacktop/cuckoo:2.0
    container_name: cuckooapi
    ports:
      - "8000:1337"
    command: api
    volumes:
      - /docker/cuckoo/data/cuckoo-tmp:/tmp/cuckoo-tmp/
      - /docker/cuckoo/data/cuckoo-storage:/cuckoo/storage/
    networks:
      - cuckoo
    env_file:
      - ./cuckoo/2.0/config-file.env
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  cuckoomongo:
    image: mongo
    container_name: cuckoomongo
    volumes:
      - /docker/cuckoomongo/data:/data/db/
    expose:
      - "27017"
    networks:
      - cuckoo
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  cuckooelasticsearch:
    image: blacktop/elasticsearch:5.6
    container_name: cuckooelasticsearch
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=cuckoo
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    volumes:
      - /docker/cuckooelasticsearch/data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      - cuckoo
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  cuckoopostgres:
    image: postgres
    container_name: cuckoopostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cuckoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /docker/cuckoopostgres/data:/var/lib/postgresql/data/pgdata/
    expose:
      - "5432"
    networks:
      cuckoo:
        aliases:
          - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

networks:
  cuckoo:
    ipam:
      config:
        - subnet: 192.168.255.16/28
